services:
  webserver:
    container_name: caddy
    image: caddy:2-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "91.98.146.252:80:80"
      - "2a01:4f8:c012:7d79::1:80:80"

      - "91.98.146.252:443:443"
      - "2a01:4f8:c012:7d79::1:443:443"

      - "91.98.146.252:443:443/udp"
      - "2a01:4f8:c012:7d79::1:443:443/udp"

      - "91.98.146.252:8443:8443"
      - "2a01:4f8:c012:7d79::1:8443:8443"

      - "91.98.146.252:8443:8443/udp"
      - "2a01:4f8:c012:7d79::1:8443:8443/udp"
    networks:
      - reverse_proxy
    volumes:
      - ./conf:/etc/caddy
      - ./data:/data
      - ./config:/config

networks:
  reverse_proxy:
    name: reverse_proxy

#volumes:
#  nextcloud:
#    external: true
