services:
  pages:
    image: 'codeberg.org/codeberg/pages-server:latest'
    container_name: 'forgejo_pages'
    working_dir: /data
    environment:
      ACME_ACCEPT_TERMS: true
      GITEA_ROOT: 'https://git.ebbez.dev'
      GITEA_API_TOKEN: '<TOKEN WITH READ>'
      PAGES_DOMAIN: 'pages.ebbez.dev'
      RAW_DOMAIN: 'raw.pages.ebbez.dev'
      NO_DNS_01: true
    ports:
      - "116.202.7.204:443:443"
      - "2a01:4f8:c012:7d79::2:443:443"
    volumes:
      - './data:/data'
