services:
  webserver:
    container_name: caddy
    image: caddy:2-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "8443:8443"
      - "8443:8443/udp"
    networks:
      - reverse_proxy
    volumes:
      - ./conf:/etc/caddy
      - ./data:/data
      - ./config:/config

networks:
  reverse_proxy:
    name: reverse_proxy

#volumes:
#  nextcloud:
#    external: true
