services:
  server:
    container_name: forgejo_server
    image: codeberg.org/forgejo/forgejo:11
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    networks:
      - default
      - reverse_proxy
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '222:22'

  docker-in-docker:
    image: docker:dind
    container_name: 'docker_dind'
    privileged: 'true'
    command: ['dockerd', '-H', 'tcp://0.0.0.0:2375', '--tls=false']
    restart: 'unless-stopped'

  forgejo-runner:
    image: 'data.forgejo.org/forgejo/runner:4.0.0'
    links:
      - docker-in-docker
      - server
    depends_on:
      docker-in-docker:
        condition: service_started
      server:
        condition: service_started
    container_name: 'runner'
    environment:
      DOCKER_HOST: tcp://docker-in-docker:2375
    # User without root privileges, but with access to `./data`.
    user: 1001:1001
    volumes:
      - ./runnerdata:/data
    restart: 'unless-stopped'
    command: '/bin/sh -c "sleep 5; forgejo-runner daemon"'

networks:
  reverse_proxy:
    external: true
  default:
