services:
  main:
    container_name: nextcloud
    image: nextcloud:32-fpm-alpine
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
      - /mnt/nextcloud:/opt/nextcloud
    networks:
      - reverse_proxy

volumes:
  nextcloud:
    name: nextcloud

networks:
  reverse_proxy:
    external: true
