services:
  server:
    image: codeberg.org/forgejo/forgejo:11
    container_name: 'forgejo_server'
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    networks:
      - default
      - reverse_proxy
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '222:22'

  docker-in-docker:
    image: docker:dind
    container_name: 'docker_dind'
    privileged: 'true'
    command: ['dockerd', '-H', 'tcp://0.0.0.0:2375', '--tls=false']
    restart: 'unless-stopped'

  runner:
    image: 'data.forgejo.org/forgejo/runner:11'
    container_name: 'forgejo_runner'
    links:
      - docker-in-docker
      - server
    depends_on:
      docker-in-docker:
        condition: service_started
      server:
        condition: service_started
    environment:
      DOCKER_HOST: tcp://docker-in-docker:2375
    # User without root privileges, but with access to `./data`.
    user: 1001:1001
    volumes:
      - ./runnerdata:/data
    restart: 'unless-stopped'
    # to register start container with (and see REGISTER.md after):
    #command: '/bin/sh -c "while : ; do sleep 1 ; done ;"'
    # to run (when registered):
    command: '/bin/sh -c "sleep 5; forgejo-runner daemon"'
  
  pages:
    image: 'codeberg.org/git-pages/git-pages:latest'
    container_name: 'forgejo_pages'
    restart: unless-stopped
    user: 1002:1002
    volumes:
      - './pages:/app'
    networks:
      - reverse_proxy
      - default

networks:
  reverse_proxy:
    external: true
